# ./docker-compose.yml

version: '3'

services:
  single-page-web:
    # image: mattrayner/lamp:latest-1604-php7
    build: ./laravel-php7
    container_name: single-page-web
    volumes:
      - ../_ref/startbootstrap-landing-page/:/app

    ports:
      - "8001:80"

    # stdin_open: true
    # tty: true
    restart: always
    networks:
        - proxy
    labels:
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:hello.louislabs.com"
        - "traefik.basic.port=80"
        - "traefik.basic.protocol=http"

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    labels:
      - traefik.backend=mosquitto
      - traefik.frontend.rule=Host:mosquitto.louislabs.com
      - traefik.frontend.entryPoints=https
      - traefik.port=9001
      - traefik.enable=true


networks:
  proxy:
    external: true
